In [3]:
import cupy as np
a_=np.array([[[3,1],[4,2],[3,4]]])

b_=np.array([[5,6],[7,8]])
#print(b_.shape[1])
#np.concatenate((a_,b_),axis=1)
print(a_.reshape([-1,1,3]))
a__=list([1,2])
print(10*a_)


[[[3 1 4]]

 [[2 3 4]]]
[[[30 10]
  [40 20]
  [30 40]]]
