In [13]:
import numpy as np
print(np.arange(8))
a=np.arange(8).reshape(2,2,2)
print(a)
print(a.reshape(2,4))
print(list(a))
print(a.transpose(0,2,1)) # 1, 2, 0

[0 1 2 3 4 5 6 7]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[0 1 2 3]
 [4 5 6 7]]
[array([[0, 1],
       [2, 3]]), array([[4, 5],
       [6, 7]])]
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]
